### ISSUE TITLE
Possible problem with ver 1.0.6

### ISSUE THREAD

**Issue by jgilcas** [fbelavenuto/msxsdmapper#1]
Hi.

I think there is a problem in version 1.0.6.
When writing to the SD card the file system is corrupted.
I have tried with previous version (1.0.4) and is working ok.

Thank you.

**Comment by rapiqui** [comment]
Hi.
I can confirm that I am experiencing the same issues exposed by @jgilcas.
Using the 1.06 version I get eventual data corruption on the SD, becoming this non usable.

I've tried several SD brands and sizes, and altough it's somehow a random pattern, they do get corrupted after some SDMapper usage.

Thanks!

**Comment by Emily82** [comment]
I confirm too. Just flashed new beta 2 kernel version and as i write to SD filesystem is corrupted.

**Comment by Emily82** [comment]
I tried latest alpha2 version built SDMAPPER.ROM from older commits in Belavenuto's github page (commit 9cca901cadc1501308d6b337f174472c8b41a7b6) 

Flashed it and i discovered that it still corrupts the filesystem!

It seems that bug occurred not with Nextor beta2 support but before!

**Comment by Emily82** [comment]
I found a possible problem related to this issue.

In `driver.asm` variable `CODE_ADD` value is `0F84Ch` but in Nextor version beta 2 this variable has changed.

Its new value is `F1D0h`. (Breaking Change)
Check here https://github.com/Konamiman/Nextor/releases

**Comment by FabianoAmerico** [comment]
Hello, Fabio.
Same problem here. SD Card gets corrupted after write anything on it after the update. Any tip to fix it?
Enfrentando o mesmo problema aqui. SD card corrompido ao gravar algo nele após a atualização. Alguma dica para reparar?

**Comment by Emily82** [comment]
And 1.04 version was removed from tags, considering its the only stable working version

**Comment by FabianoAmerico** [comment]
> And 1.04 version was removed from tags, considering its the only stable working version

I found a way to return to version 1.0.4 and fix everything!
Using the SDMAPPER_patch_ciel2+.ROM file (https://github.com/fbelavenuto/msxsdmapper/tree/master/Driver) to rewrite the EPROM.
Now everything is back to normal, that is, no more corrupted SD cards!

Eu consegui uma maneira de retornar para a versão 1.0.4 e consertar tudo!
Utilizando o arquivo SDMAPPER_patch_ciel2+.ROM (https://github.com/fbelavenuto/msxsdmapper/tree/master/Driver) para reescrever a EPROM.
Agora tudo voltou ao normal, ou seja, sem cartões SD corrompidos!

**Comment by fbelavenuto** [comment]
Hi Guys, please test this ROM:

https://github.com/fbelavenuto/msxsdmapper/blob/fixdriver/driver/SDMAPPER.ROM

**Comment by FabianoAmerico** [comment]
> Hi Guys, please test this ROM:
> 
> https://github.com/fbelavenuto/msxsdmapper/blob/fixdriver/driver/SDMAPPER.ROM

Nope... Lost everything on the SD Card again even with this new version.

**Comment by fbelavenuto** [comment]
Bug fixed, please test with latest release (SDMAPPER.ROM was updated)

**Comment by Emily82** [comment]
I just tested the latest sdmapper.rom with the latest smupd.com, flashed it but the problem isnt fixed. I created a text file with ted.com and it gets corrupted, it was renamed with garbage characters.

Now i flashed it back to old 1.04 and it works well.

**Comment by fbelavenuto** [comment]
Fixed, get the latest version on release page (1.0.7)

**Comment by Emily82** [comment]
Yea it works now! I tested it and it seems also faster copying files from my gotek to sd. Before with 1.04 version it was very slow.
