### ISSUE TITLE
Is it safe to update an older 8bits4ever SD-512 to 1.0.7?

### ISSUE THREAD

**Issue by mfeingol** [fbelavenuto/msxsdmapper#10]
I have an 8bits4ever SD-512 from 2016. It's the older model with one switch to enable/disable the memory mapper. It comes with version 1.0.4 and an older Nextor.

Is it safe to update this unit to version 1.0.7? 8bits4ever told me there was a possibility that it could brick the unit.

Thanks.

**Comment by fbelavenuto** [comment]
Hi, yes, it's safe.

**Comment by mfeingol** [comment]
Thanks. Should `SDMUPD.com` be run from the SD card itself, or from a floppy disk?

**Comment by fbelavenuto** [comment]
> Thanks. Should `SDMUPD.com` be run from the SD card itself, or from a floppy disk?

Another device. Uses a floppy or another mass storage device.

**Comment by mfeingol** [comment]
I wonder if people reporting bricked devices are running the update from the same device, and that's what's leading to problems?

**Comment by fbelavenuto** [comment]
> I wonder if people reporting bricked devices are running the update from the same device, and that's what's leading to problems?

Yes, that's what causes problems. If the MSX boots with the interface bricked, you can still try to reburn the firmware.

**Comment by mfeingol** [comment]
Flashed successfully, thank you. A scary moment when after erasing the mapper for the first time, the MSX rebooted. Running the update again did the trick. Good thing I had MSX-DOS on the floppy. :-)
